<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %s Talend Technology%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have landed on Talend Technology tutorial'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
   
</div>

<div class="row">
<?php 
$courses = $this->courses;
foreach ($courses as $key => $value) {   } ?>
    <div class="col-md-3 small_3_3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('DI') ?></h3>
            </div>
            <div class="panel-body small_3_3">
                <p><?php echo sprintf($this->translate('Data Integration is a tool to connect data in fast and cost effetcive way !!! See %sData Integration%s'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="https://www.talend.com/products/data-integration/">') ?></p>
            </div>
        </div>
    </div>
    <div class="col-md-3 small_3_3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Data Preparation') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Data preparation is a collaboration tool!!! Demand for data is dramatically increasing as enterprises become data-driven. IT is struggling to meet the data needs of the business, and as a result, data analysts are spending up to 80 Percent of their time cleaning data . %sData Preparations%s'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>') ?></p>
            </div>
        </div>
    </div>
    <div class="col-md-3 small_3_3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('DQ') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Talend Data Quality has the potential to reduce costs, increase sales, and improve performance by making trusted data available in every style of integration. Talend Data Quality delivers trusted data everywhere with easy onboarding, standards, and rules application across all Talend integration platforms. %s Data Quality %s'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>') ?></p>
            </div>
        </div>
    </div>
    <div class="col-md-3 small_3_3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('ESB') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
            </div>
        </div>
    </div>
    <div class="col-md-3 small_3_3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('MDM') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
            </div>
        </div>
    </div>
    <div class="col-md-3 small_3_3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Big Data') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
            </div>
        </div>
    </div>
     
     
</div>
